### ISSUE TITLE
Getting the froze pose instead of the spongy one

### ISSUE THREAD

**Issue by aless98** [microsoft/MixedReality-WorldLockingTools-Samples#82] opened 2022-04-01 11:44 UTC
Hello!
I am trying to access the frozen pose of the QRcode using
Pose frozen_pose = WorldLockingManager.GetInstance().FrozenFromSpongy;
Unluckily there is no so much on the internet as i could see. Is it the correct way to do it?
I have also tried to use WorldLockingManager.GetInstance().FrozenFromSpongy.Multiply(CurrentspongyPose) but the pose is pretty much the same as the spongy one. Do you have any suggestion? Basically what i am trying to do is to align an holographic cube witha real one and if i am close the allignment is good but as soon a si move around it or far from it the hologram shifts. Is it related to the world locking ?
Thank you in advance!

Alessandro.

**Comment by fast-slow-still** [comment] 2022-04-08 08:07
Hi @aless98, I'm closing this as a duplicate of your issue submitted to the main world locking tools repo. In general, it's a bad idea to post the same issue multiple times in multiple places.

Apologies on the delay on responding, but I've been away.

https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/issues/276

Thanks!

**Closed by fast-slow-still** 2022-04-08 08:07 UTC
